### ISSUE TITLE
Where is the data set being referenced everywhere?

### ISSUE THREAD

**Issue by pranny** [MichaelMure/3DMM#3]
Could you release the "data" directory as a part of this repo? Would be great help. Thanks!

**Comment by MichaelMure** [comment]
Sorry but no.

To use the code as is, you will need to ask for an access to the Basel
Face Model database
(http://faces.cs.unibas.ch/bfm/main.php?nav=1-1-0&id=details). As per
the license as the database, I'm not allowed to redistribute it.

**Comment by pranny** [comment]
Thanks, That's useful :)
