### ISSUE TITLE
Where can I find your internship report?

### ISSUE THREAD

**Issue by chenkezhe** [MichaelMure/3DMM#5]
Hello, thanks for sharing this, and I want to know the detail of the implement of 3DMM, could you tell how to get your internship report.

**Comment by MichaelMure** [comment]
Hello,

You will find my internship report here: http://pellelatarte.fr/dl/Michael_Mur%C3%A9-internship_report.pdf

**Comment by mohanen** [comment]
This was really helpful, cleared some doubts in the original paper.
